spring.application.name=demo

# DB接続設定
spring.datasource.url=jdbc:postgresql://localhost:5432/taskdb
spring.datasource.username=defaultuser
spring.datasource.password=a@bBcCdD
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate設定
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# エンティティ定義に合わせて自動でテーブル作成・更新を行う（開発時用: update / 検証用: validate）
spring.jpa.hibernate.ddl-auto=update
# SQLログを出力する場合
spring.jpa.show-sql=true